default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fruit_app_development

test:
  <<: *default
  database: fruit_app_test

production:
  <<: *default
  database: fruit_app_production
  username: fruit_app
  password: <%= ENV['FRUIT_APP_DATABASE_PASSWORD'] %>
